package org.hyperscala

sealed abstract class Protocol(val scheme: String, val description: String, val rfc: String) {
  Protocol.schemeMap += scheme -> this

  override def toString = scheme
}

object Protocol {
  private var schemeMap = Map.empty[String, Protocol]

  case object Aaa extends Protocol("aaa", "Diameter Protocol","RFC6733")
  case object Aaas extends Protocol("aaas", "Diameter Protocol with Secure Transport", "RFC6733")
  case object About extends Protocol("about", "about", "RFC6694")
  case object Acap extends Protocol("acap", "application configuration access protocol", "RFC2244")
  case object Acct extends Protocol("acct", "acct", "RFC-ietf-appsawg-acct-uri-06")
  case object Cap extends Protocol("cap", "Calendar Access Protocol", "RFC4324")
  case object Cid extends Protocol("cid", "content identifier", "RFC2392")
  case object Coap extends Protocol("coap", "coap", "RFC-ietf-core-coap-18")
  case object Coaps extends Protocol("coaps", "coaps", "RFC-ietf-core-coap-18")
  case object Crid extends Protocol("crid", "TV-Anytime Content Reference Identifier", "RFC4078")
  case object Data extends Protocol("data", "data", "RFC2397")
  case object Dav extends Protocol("dav", "dav", "RFC4918")
  case object Dict extends Protocol("dict", "dictionary service protocol", "RFC2229")
  case object Dns extends Protocol("dns", "Domain Name System", "RFC4501")
  case object File extends Protocol("file", "Host-specific file names", "RFC1738")
  case object Ftp extends Protocol("ftp", "File Transfer Protocol", "RFC1738")
  case object Geo extends Protocol("geo", "Geographic Locations", "RFC5870")
  case object Go extends Protocol("go", "go", "RFC3368")
  case object Gopher extends Protocol("gopher", "The Gopher Protocol", "RFC4266")
  case object H323 extends Protocol("h323", "H.323", "RFC3508")
  case object Http extends Protocol("http", "Hypertext Transfer Protocol", "RFC2616")
  case object Https extends Protocol("https", "Hypertext Transfer Protocol Secure", "RFC2818")
  case object Iax extends Protocol("iax", "Inter-Asterisk eXchange Version 2", "RFC5456")
  case object Icap extends Protocol("icap", "Internet Content Adaptation Protocol", "RFC3507")
  case object Im extends Protocol("im", "Instant Messaging", "RFC3860")
  case object Imap extends Protocol("imap", "internet message access protocol", "RFC5092")
  case object Info extends Protocol("info", "Information Assets with Identifiers in Public Namespaces", "RFC4452")
  case object Ipp extends Protocol("ipp", "Internet Printing Protocol", "RFC3510")
  case object Iris extends Protocol("iris", "Internet Registry Information Service", "RFC3981")
  case object IrisBeep extends Protocol("iris.beep", "iris.beep", "RFC3983")
  case object IrisXpc extends Protocol("iris.xpc", "iris.xpc", "RFC4992")
  case object IrisXpcs extends Protocol("iris.xpcs", "iris.xpcs", "RFC4992")
  case object IrisLwz extends Protocol("iris.lwz", "iris.lwz", "RFC4993")
  case object Jabber extends Protocol("jabber", "jabber","Saint-Andre")
  case object JarFile extends Protocol("jar:file", "JAR File","JAR")
  case object Ldap extends Protocol("ldap", "Lightweight Directory Access Protocol","RFC4516")
  case object Mailto extends Protocol("mailto", "Electronic mail address", "RFC6068")
  case object Mid extends Protocol("mid", "message identifier", "RFC2392")
  case object Msrp extends Protocol("msrp", "Message Session Relay Protocol", "RFC4975")
  case object Msrps extends Protocol("msrps", "Message Session Relay Protocol Secure", "RFC4975")
  case object Mtqp extends Protocol("mtqp", "Message Tracking Query Protocol", "RFC3887")
  case object Mupdate extends Protocol("mupdate", "Mailbox Update (MUPDATE) Protocol", "RFC3656")
  case object News extends Protocol("news", "USENET news", "RFC5538")
  case object Nfs extends Protocol("nfs", "network file system protocol", "RFC2224")
  case object Ni extends Protocol("ni", "ni", "RFC6920")
  case object Nih extends Protocol("nih", "nih", "RFC6920")
  case object Nntp extends Protocol("nntp", "USENET news using NNTP access", "RFC5538")
  case object Opaquelocktoken extends Protocol("opaquelocktoken", "opaquelocktokent", "RFC4918")
  case object Pop extends Protocol("pop", "Post Office Protocol v3", "RFC2384")
  case object Pres extends Protocol("pres", "Presence", "RFC3859")
  case object Reload extends Protocol("reload", "reload","draft-ietf-p2psip-base-26")
  case object Rtsp extends Protocol("rtsp", "real time streaming protocol", "RFC2326")
  case object Service extends Protocol("service", "service location", "RFC2609")
  case object Session extends Protocol("session", "session", "RFC6787")
  case object Shttp extends Protocol("shttp", "Secure Hypertext Transfer Protocol", "RFC2660")
  case object Sieve extends Protocol("sieve", "ManageSieve Protocol", "RFC5804")
  case object Sip extends Protocol("sip", "session initiation protocol", "RFC3261")
  case object Sips extends Protocol("sips", "secure session initiation protocol", "RFC3261")
  case object Sms extends Protocol("sms", "Short Message Service", "RFC5724")
  case object Snmp extends Protocol("snmp", "Simple Network Management Protocol", "RFC4088")
  case object SoapBeep extends Protocol("soap.beep", "soap.beep", "RFC4227")
  case object SoapBeeps extends Protocol("soap.beeps", "soap.beeps", "RFC4227")
  case object Tag extends Protocol("tag", "tag", "RFC4151")
  case object Tel extends Protocol("tel", "telephone", "RFC3966")
  case object Telnet extends Protocol("telnet", "Reference to interactive sessions", "RFC4248")
  case object Tftp extends Protocol("tftp", "Trivial File Transfer Protocol", "RFC3617")
  case object Thismessage extends Protocol("thismessage", "perm/thismessage	multipart/related relative reference resolution", "RFC2557")
  case object Tn3270 extends Protocol("tn3270", "Interactive 3270 emulation sessions", "RFC6270")
  case object Tip extends Protocol("tip", "Transaction Internet Protocol", "RFC2371")
  case object Tv extends Protocol("tv", "TV Broadcasts", "RFC2838")
  case object Urn extends Protocol("urn", "Uniform Resource Names", "RFC2141][IANA registry urn-namespaces")
  case object Vemmi extends Protocol("vemmi", "versatile multimedia interface", "RFC2122")
  case object Ws extends Protocol("ws", "WebSocket connections", "RFC6455")
  case object Wss extends Protocol("wss", "Encrypted WebSocket connections", "RFC6455")
  case object Xcon extends Protocol("xcon", "xcon", "RFC6501")
  case object XconUserid extends Protocol("xcon-userid", "xcon-userid", "RFC6501")
  case object XmlrpcBeep extends Protocol("xmlrpc.beep", "xmlrpc.beep", "RFC3529")
  case object XmlrpcBeeps extends Protocol("xmlrpc.beeps", "xmlrpc.beeps", "RFC3529")
  case object Xmpp extends Protocol("xmpp", "Extensible Messaging and Presence Protocol", "RFC5122")
  case object Z3950r extends Protocol("z39.50r", "Z39.50 Retrieval", "RFC2056")
  case object Z3950s extends Protocol("z39.50s", "Z39.50 Session", "RFC2056")

  def apply(scheme: String): Protocol = schemeMap(scheme.toLowerCase)
}